on:
  push:
    branches:
    - master
jobs:
  adoc_build_web:
    runs-on: ubuntu-latest
    name: Build CV 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Convert AsciiDoc step
      id: documents
      uses: Analog-inc/asciidoctor-action@master
      with:
        shellcommand: "./.github/workflows/asciidoc.sh"  
    - name: Print execution time
      run: echo "Time ${{ steps.adocbuild.outputs.time }}"
    - name: Deploy docs to ghpages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./outputs/html
    - name: Save AsciiDoc step
      uses: actions/upload-artifact@v1
      with:
        name: Docs
        path: ./outputs/pdf/
    - name: Github Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The name of the release to publish
        title: CV
        # Directory of the repository that the should create the release
        workdir: ./outputs/pdf/
